apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: bookstore-ingress
spec:
  rules:
  - host: bookstore.ingress.kube.com
    http:
      paths:
      - path: /
        backend:
          serviceName: bookstore-api
          servicePort: 8080
